[package]
org = "WSO2"
name = "manage_deals"
version = "0.1.0"

[build-options]
observabilityIncluded = true
[[dependency]]
org = "ballerinax"
name = "hubspot.crm.obj.deals"
version = "0.1.0"
repository = "local"